# Generated by Django 4.0.6 on 2022-07-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('desc', models.TextField(verbose_name='Description')),
                ('img', models.ImageField(default=False, upload_to='images/shops')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task Category', 'verbose_name_plural': 'Task Categories'},
        ),
    ]
