# Generated by Django 4.0.6 on 2022-07-26 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shops_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='img',
            field=models.ImageField(default=False, upload_to='main/images/shops'),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('desc', models.TextField(verbose_name='Description')),
                ('price', models.IntegerField(default=0)),
                ('img', models.ImageField(default=False, upload_to='main/images/shops')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.shops')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
