# Generated by Django 4.0.6 on 2022-07-26 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_products_is_active_shops_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['category', 'title'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.shops', verbose_name='shop'),
        ),
        migrations.AlterField(
            model_name='products',
            name='desc',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(default=False, upload_to='main/images/shops', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
