# Generated by Django 4.0.6 on 2022-07-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_products_options_alter_products_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shops',
            options={'ordering': ['title'], 'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
        migrations.AlterField(
            model_name='shops',
            name='desc',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='img',
            field=models.ImageField(default=False, upload_to='main/images/shops', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='title',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
