# Generated by Django 4.0.6 on 2022-07-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_shops_options_alter_shops_desc_alter_shops_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(default=False, upload_to='images/shops', verbose_name='image'),
        ),
    ]
