# Generated by Django 4.0.6 on 2022-07-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_products_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(default=False, upload_to='main/images', verbose_name='image'),
        ),
    ]
